spring:
  application:
    name: eureka-server
server:
  port: 9010
eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:9010/eureka #单机版服务注册中心